FROM texlive/texlive:latest-full

# Install additional packages
RUN apt-get update && apt-get install -y --no-install-recommends --no-install-suggests \
    wget \
    fonts-noto-cjk \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ENV SHELL=/bin/bash
RUN bash -c "$(curl -fsSL https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh)"
